coverage:
  status:
    project:
      default: false
      app:
        target: 90%
        threshold: 0%
        base: auto
        flags: 
          - integration
        paths: 
          - "src" 
          - "!tests/"