coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: pr
        flags: 
          - integration
        paths: 
          - "src"
        only_pulls: true 
     # tests:  # declare a new status context "tests"
     #   target: 100%  # we always want 100% coverage here
     #   paths: "tests/"  # only include coverage in "tests/" folder
     # app:  # declare a new status context "app"
     #   paths: "!tests/"  # remove all files in "tests/"