version: "3"

services:
  # The application image
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APPLICATION_ENV: development
    working_dir: /var/www/node
    volumes:
      - ./:/var/www/node
      - ./node_modules:/var/www/node/node_modules
     # - /usr/local/lib/node_modules/@madeiramadeirabr/service-codebase-core:/usr/local/lib/node_modules/@madeiramadeirabr/service-codebase-core
    links:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229

  # The db manager image
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mongo

  # The db image
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
