name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

  # Runs a single command using the runners shell
    - name: Run a one-line script
    - name: Super-Linter
      uses: github/super-linter@v3.3.0
